name: Ubuntu-18-04

on: 
  push:
    branches:
      - dev_lesthack_lastfm

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [6.17.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Requirements
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install g++-multilib lib32z1 lib32ncurses5 rpm fakeroot dpkg libdbus-1-dev libx11-dev g++ libavahi-compat-libdnssd-dev gcc-4.8-multilib g++-4.8-multilib libnotify4 libexpat1-dev libbz2-1.0 -y

      - name: npm
        run: |
          npm install
          npm run build
